// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	app.proto

It has these top-level messages:
	AppBundle
	AppBundleKeySet
	AppDescriptor
	AppDescriptors
	Query
	QueryResult
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Query_ObjectType int32

const (
	Query_APP_DESCRIPTOR Query_ObjectType = 0
	Query_APP_BUNDLE     Query_ObjectType = 1
)

var Query_ObjectType_name = map[int32]string{
	0: "APP_DESCRIPTOR",
	1: "APP_BUNDLE",
}
var Query_ObjectType_value = map[string]int32{
	"APP_DESCRIPTOR": 0,
	"APP_BUNDLE":     1,
}

func (x Query_ObjectType) String() string {
	return proto.EnumName(Query_ObjectType_name, int32(x))
}
func (Query_ObjectType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type AppBundle struct {
	Owner                    []byte   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	DescriptorId             string   `protobuf:"bytes,2,opt,name=descriptor_id,json=descriptorId" json:"descriptor_id,omitempty"`
	Artifacts                [][]byte `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	ChaincodeDeploymentSpecs [][]byte `protobuf:"bytes,4,rep,name=chaincode_deployment_specs,json=chaincodeDeploymentSpecs,proto3" json:"chaincode_deployment_specs,omitempty"`
	// The endorsements of the above deployment spec, the owner's signature over
	// artifacts[] + chaincode_deployment_spec[] + Endorsement.endorser.
	OwnerEndorsements [][]byte `protobuf:"bytes,5,rep,name=owner_endorsements,json=ownerEndorsements,proto3" json:"owner_endorsements,omitempty"`
}

func (m *AppBundle) Reset()                    { *m = AppBundle{} }
func (m *AppBundle) String() string            { return proto.CompactTextString(m) }
func (*AppBundle) ProtoMessage()               {}
func (*AppBundle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppBundle) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *AppBundle) GetDescriptorId() string {
	if m != nil {
		return m.DescriptorId
	}
	return ""
}

func (m *AppBundle) GetArtifacts() [][]byte {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

func (m *AppBundle) GetChaincodeDeploymentSpecs() [][]byte {
	if m != nil {
		return m.ChaincodeDeploymentSpecs
	}
	return nil
}

func (m *AppBundle) GetOwnerEndorsements() [][]byte {
	if m != nil {
		return m.OwnerEndorsements
	}
	return nil
}

type AppBundleKeySet struct {
	DescriptorId string   `protobuf:"bytes,1,opt,name=descriptor_id,json=descriptorId" json:"descriptor_id,omitempty"`
	BundleKeys   []string `protobuf:"bytes,2,rep,name=bundle_keys,json=bundleKeys" json:"bundle_keys,omitempty"`
}

func (m *AppBundleKeySet) Reset()                    { *m = AppBundleKeySet{} }
func (m *AppBundleKeySet) String() string            { return proto.CompactTextString(m) }
func (*AppBundleKeySet) ProtoMessage()               {}
func (*AppBundleKeySet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppBundleKeySet) GetDescriptorId() string {
	if m != nil {
		return m.DescriptorId
	}
	return ""
}

func (m *AppBundleKeySet) GetBundleKeys() []string {
	if m != nil {
		return m.BundleKeys
	}
	return nil
}

type AppDescriptor struct {
	Owner       []byte `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	BundleId    string `protobuf:"bytes,3,opt,name=bundle_id,json=bundleId" json:"bundle_id,omitempty"`
}

func (m *AppDescriptor) Reset()                    { *m = AppDescriptor{} }
func (m *AppDescriptor) String() string            { return proto.CompactTextString(m) }
func (*AppDescriptor) ProtoMessage()               {}
func (*AppDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppDescriptor) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *AppDescriptor) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppDescriptor) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

type AppDescriptors struct {
	Descriptors map[string]*AppDescriptor `protobuf:"bytes,3,rep,name=descriptors" json:"descriptors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AppDescriptors) Reset()                    { *m = AppDescriptors{} }
func (m *AppDescriptors) String() string            { return proto.CompactTextString(m) }
func (*AppDescriptors) ProtoMessage()               {}
func (*AppDescriptors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AppDescriptors) GetDescriptors() map[string]*AppDescriptor {
	if m != nil {
		return m.Descriptors
	}
	return nil
}

type Query struct {
	ObjectType   Query_ObjectType `protobuf:"varint,1,opt,name=object_type,json=objectType,enum=main.Query_ObjectType" json:"object_type,omitempty"`
	KeyParts     []string         `protobuf:"bytes,2,rep,name=key_parts,json=keyParts" json:"key_parts,omitempty"`
	Offset       uint32           `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	ReturnValues bool             `protobuf:"varint,4,opt,name=return_values,json=returnValues" json:"return_values,omitempty"`
	MaxCount     uint32           `protobuf:"varint,5,opt,name=max_count,json=maxCount" json:"max_count,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Query) GetObjectType() Query_ObjectType {
	if m != nil {
		return m.ObjectType
	}
	return Query_APP_DESCRIPTOR
}

func (m *Query) GetKeyParts() []string {
	if m != nil {
		return m.KeyParts
	}
	return nil
}

func (m *Query) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Query) GetReturnValues() bool {
	if m != nil {
		return m.ReturnValues
	}
	return false
}

func (m *Query) GetMaxCount() uint32 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

type QueryResult struct {
	Query   *Query            `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	HasMore bool              `protobuf:"varint,2,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	Results map[string][]byte `protobuf:"bytes,3,rep,name=results" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *QueryResult) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *QueryResult) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *QueryResult) GetResults() map[string][]byte {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*AppBundle)(nil), "main.AppBundle")
	proto.RegisterType((*AppBundleKeySet)(nil), "main.AppBundleKeySet")
	proto.RegisterType((*AppDescriptor)(nil), "main.AppDescriptor")
	proto.RegisterType((*AppDescriptors)(nil), "main.AppDescriptors")
	proto.RegisterType((*Query)(nil), "main.Query")
	proto.RegisterType((*QueryResult)(nil), "main.QueryResult")
	proto.RegisterEnum("main.Query_ObjectType", Query_ObjectType_name, Query_ObjectType_value)
}

func init() { proto.RegisterFile("app.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0xdc, 0xd4, 0xad, 0x3d, 0x76, 0xf3, 0x85, 0xa5, 0xaa, 0x4c, 0x41, 0x10, 0x8c, 0x90,
	0xc2, 0x05, 0x16, 0x0a, 0x17, 0x54, 0x15, 0x37, 0x6d, 0x13, 0xa1, 0x8a, 0x9f, 0x86, 0x4d, 0x81,
	0x4b, 0xcb, 0xb1, 0xa7, 0xaa, 0x49, 0xe2, 0x5d, 0x76, 0xd7, 0x50, 0xbf, 0x14, 0xef, 0xc0, 0x23,
	0xf0, 0x18, 0xbc, 0x05, 0xda, 0x75, 0x7e, 0x5c, 0x28, 0x57, 0xd9, 0x99, 0x73, 0xce, 0xec, 0xce,
	0x39, 0x91, 0xc1, 0x4d, 0x38, 0x8f, 0xb8, 0x60, 0x8a, 0x91, 0xcd, 0x79, 0x92, 0x17, 0xe1, 0x4f,
	0x0b, 0xdc, 0x23, 0xce, 0x8f, 0xcb, 0x22, 0x9b, 0x21, 0xd9, 0x05, 0x9b, 0x7d, 0x2b, 0x50, 0x04,
	0x56, 0xd7, 0xea, 0xf9, 0xb4, 0x2e, 0xc8, 0x23, 0xd8, 0xc9, 0x50, 0xa6, 0x22, 0xe7, 0x8a, 0x89,
	0x38, 0xcf, 0x82, 0x8d, 0xae, 0xd5, 0x73, 0xa9, 0xbf, 0x6e, 0x9e, 0x66, 0xe4, 0x1e, 0xb8, 0x89,
	0x50, 0xf9, 0x45, 0x92, 0x2a, 0x19, 0xb4, 0xba, 0xad, 0x9e, 0x4f, 0xd7, 0x0d, 0xf2, 0x12, 0xf6,
	0xd3, 0xcb, 0x24, 0x2f, 0x52, 0x96, 0x61, 0x9c, 0x21, 0x9f, 0xb1, 0x6a, 0x8e, 0x85, 0x8a, 0x25,
	0xc7, 0x54, 0x06, 0x9b, 0x86, 0x1e, 0xac, 0x18, 0x83, 0x15, 0x61, 0xac, 0x71, 0xf2, 0x14, 0x88,
	0x79, 0x49, 0x8c, 0x45, 0xc6, 0x84, 0x44, 0x8d, 0xc8, 0xc0, 0x36, 0xaa, 0x5b, 0x06, 0x19, 0x36,
	0x80, 0xf0, 0x13, 0xfc, 0xbf, 0x5a, 0xe9, 0x35, 0x56, 0x63, 0x54, 0x7f, 0xaf, 0x60, 0xdd, 0xb0,
	0xc2, 0x03, 0xf0, 0x26, 0x46, 0x14, 0x4f, 0xb1, 0x92, 0xc1, 0x46, 0xb7, 0xd5, 0x73, 0x29, 0x4c,
	0x96, 0x73, 0x64, 0x98, 0xc1, 0xce, 0x11, 0xe7, 0x83, 0x95, 0xe6, 0x1f, 0x7e, 0x75, 0xc1, 0x5b,
	0xce, 0xcd, 0x59, 0xb1, 0x70, 0xab, 0xd9, 0x22, 0x77, 0xc1, 0x5d, 0xdc, 0x94, 0x67, 0x41, 0xcb,
	0xe0, 0x4e, 0xdd, 0x38, 0xcd, 0xc2, 0xef, 0x16, 0xb4, 0xaf, 0x5d, 0x23, 0xc9, 0xab, 0xf5, 0x44,
	0x26, 0x6a, 0x7b, 0xbd, 0xfe, 0xe3, 0x48, 0x27, 0x18, 0x5d, 0xa7, 0x46, 0x8d, 0xf3, 0xb0, 0x50,
	0xa2, 0xa2, 0x4d, 0xe5, 0xfe, 0x18, 0x3a, 0x7f, 0x12, 0x48, 0x07, 0x5a, 0x53, 0xac, 0x16, 0x8e,
	0xe8, 0x23, 0x79, 0x02, 0xf6, 0xd7, 0x64, 0x56, 0xa2, 0x79, 0xba, 0xd7, 0xbf, 0x7d, 0xc3, 0x45,
	0xb4, 0x66, 0x1c, 0x6e, 0x1c, 0x58, 0xe1, 0x2f, 0x0b, 0xec, 0xf7, 0x25, 0x8a, 0x8a, 0xbc, 0x00,
	0x8f, 0x4d, 0x3e, 0x63, 0xaa, 0x62, 0x55, 0x71, 0x34, 0x23, 0xdb, 0xfd, 0xbd, 0x5a, 0x6e, 0x18,
	0xd1, 0x99, 0x81, 0xcf, 0x2b, 0x8e, 0x14, 0xd8, 0xea, 0xac, 0x0d, 0x99, 0x62, 0x15, 0xf3, 0x44,
	0xa8, 0xa5, 0xf1, 0xce, 0x14, 0xab, 0x91, 0xae, 0xc9, 0x1e, 0x6c, 0xb1, 0x8b, 0x0b, 0x89, 0xca,
	0x58, 0xb5, 0x43, 0x17, 0x95, 0x0e, 0x55, 0xa0, 0x2a, 0x45, 0x11, 0x9b, 0xb7, 0xe8, 0xff, 0x91,
	0xd5, 0x73, 0xa8, 0x5f, 0x37, 0x3f, 0x9a, 0x9e, 0x9e, 0x3c, 0x4f, 0xae, 0xe2, 0x94, 0x95, 0x85,
	0x0a, 0x6c, 0xa3, 0x77, 0xe6, 0xc9, 0xd5, 0x89, 0xae, 0xc3, 0x67, 0x00, 0xeb, 0x07, 0x11, 0x02,
	0xed, 0xa3, 0xd1, 0x28, 0x1e, 0x0c, 0xc7, 0x27, 0xf4, 0x74, 0x74, 0x7e, 0x46, 0x3b, 0xff, 0x91,
	0x36, 0x80, 0xee, 0x1d, 0x7f, 0x78, 0x37, 0x78, 0x33, 0xec, 0x58, 0xe1, 0x0f, 0x0b, 0x3c, 0xb3,
	0x09, 0x45, 0x59, 0xce, 0x14, 0x79, 0x08, 0xf6, 0x17, 0x5d, 0x9a, 0x5d, 0xbd, 0xbe, 0xd7, 0xd8,
	0x95, 0xd6, 0x08, 0xb9, 0x03, 0xce, 0x65, 0x22, 0xe3, 0x39, 0x13, 0xb5, 0xa1, 0x0e, 0xdd, 0xbe,
	0x4c, 0xe4, 0x5b, 0x26, 0x90, 0x1c, 0xc0, 0xb6, 0x30, 0x73, 0x96, 0x99, 0xde, 0x6f, 0xea, 0x0d,
	0x12, 0xd5, 0x3f, 0x8b, 0x30, 0x97, 0xf4, 0xfd, 0x43, 0xf0, 0x9b, 0xc0, 0x0d, 0x21, 0xee, 0x36,
	0x43, 0xf4, 0x1b, 0x79, 0x4d, 0xb6, 0xcc, 0x07, 0xe0, 0xf9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xde, 0x34, 0x6a, 0xa3, 0x0d, 0x04, 0x00, 0x00,
}
